include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    use_key_in_widget_constructors: true

analyzer:
  exclude:
    - build/**
    - android/**/generated/**
