import '../models/match.dart';

class MatchSheetService {
  static String generateTextReport({
    required String leagueName,
    required String homeTeam,
    required String awayTeam,
    required int homeScore,
    required int awayScore,
  }) {
    final String timestamp = DateTime.now().toString().substring(0, 16);
    
    // We use a clean, emoji-boosted format for WhatsApp
    return """
🏆 *OFFICIAL MATCH REPORT* 🏆
━━━━━━━━━━━━━━━━━━━━
🏟️ League: $leagueName
⏰ Date: $timestamp

🏁 *FINAL SCORE* 🏁
🏠 $homeTeam [$homeScore]
vs
🚀 $awayTeam [$awayScore]

━━━━━━━━━━━━━━━━━━━━
Generated by EleagueHub3
📱 Join the tournament now!
""";
  }
}
