import 'package:flutter/material.dart';
import '../../models/league_format.dart';

/// Screen to create a new league.
/// League ID & QR Code are generated by backend AFTER creation.
class CreateLeagueScreen extends StatefulWidget {
  const CreateLeagueScreen({super.key});

  @override
  State<CreateLeagueScreen> createState() => _CreateLeagueScreenState();
}

class _CreateLeagueScreenState extends State<CreateLeagueScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();

  LeagueFormat _selectedFormat = LeagueFormat.classic;
  bool _isSubmitting = false;

  Future<void> _createLeague() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isSubmitting = true);

    try {
      // TODO: Call repository / backend
      // Example:
      // await leaguesRepository.createLeague(
      //   name: _nameController.text.trim(),
      //   format: _selectedFormat.name,
      //   privacy: 'Public',
      //   region: 'Global',
      //   maxTeams: 32,
      //   forfeitEnabled: true,
      //   proofDeadlineHours: 24,
      //   tiebreakers: [],
      // );

      await Future<void>.delayed(const Duration(milliseconds: 600));

      if (!mounted) return;

      Navigator.pop(context);
    } finally {
      if (mounted) {
        setState(() => _isSubmitting = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create eSportlyic League'),
        backgroundColor:
            _selectedFormat == LeagueFormat.classic ? Colors.green : Colors.indigo,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              /// League name
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(
                  labelText: 'League Name',
                  border: OutlineInputBorder(),
                ),
                validator: (val) =>
                    val == null || val.isEmpty ? 'Enter a league name' : null,
              ),

              const SizedBox(height: 24),

              const Text(
                'Select Format:',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),

              /// Classic League
              RadioListTile<LeagueFormat>(
                title: Text(LeagueFormat.classic.displayName),
                subtitle: Text(LeagueFormat.classic.description),
                value: LeagueFormat.classic,
                groupValue: _selectedFormat,
                onChanged: (val) =>
                    setState(() => _selectedFormat = val!),
              ),

              /// UCL Group Stage
              RadioListTile<LeagueFormat>(
                title: Text(LeagueFormat.uclGroup.displayName),
                subtitle: Text(LeagueFormat.uclGroup.description),
                value: LeagueFormat.uclGroup,
                groupValue: _selectedFormat,
                onChanged: (val) =>
                    setState(() => _selectedFormat = val!),
              ),

              /// UCL Swiss Model
              RadioListTile<LeagueFormat>(
                title: Text(LeagueFormat.uclSwiss.displayName),
                subtitle: Text(LeagueFormat.uclSwiss.description),
                value: LeagueFormat.uclSwiss,
                groupValue: _selectedFormat,
                onChanged: (val) =>
                    setState(() => _selectedFormat = val!),
              ),

              const SizedBox(height: 32),

              /// Submit button
              ElevatedButton(
                onPressed: _isSubmitting ? null : _createLeague,
                child: _isSubmitting
                    ? const SizedBox(
                        height: 18,
                        width: 18,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Text('CREATE LEAGUE'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
